name: clang-format Check
on:
  pull_request:
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C programs.
      uses: DoozyX/clang-format-lint-action@v0.18.2
      with:
        source: '.'
        extensions: 'c,h,cpp,hpp'
        clangFormatVersion: 10
        style: file
        # exclude: './config'
