name: GitLab

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sync-with-gitlab:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup git
        run: |
          git config --global user.name "h5bench BOT"
          git config --global user.email "h5bench@example.com"
    
      - name: Update branch
        run: |
          git fetch master
          git remote add gitlab https://${{ secrets.GITLAB_TOKEN_NAME }}:${{ secrets.GITLAB_TOKEN }}@${{ secrets.GITLAB_URL }}
          git checkout master
          git push -f master -u gitlab