name: HDF5 1.10.7

on:
  pull_request:

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  h5bench:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          sudo apt install gcc
          sudo apt-get install libtool
          sudo apt-get install zlib1g-dev
          sudo apt-get install python3
          sudo apt-get install libopenmpi-dev
          sudo apt-get install libhdf5-mpi-dev
          
          # hdf5
          wget https://github.com/HDFGroup/hdf5/archive/refs/tags/hdf5-1_10_7.tar.gz
          tar zxvf hdf5-1_10_7.tar.gz
          mv hdf5-hdf5-1_10_7 hdf5
          
          # vol-async
          git clone --recursive https://github.com/hpc-io/vol-async.git

      - name: Build h5bench SYNC
        run: |
          mkdir build_sync
          cd build_sync
          cmake .. -DCMAKE_C_COMPILER=/usr/bin/h5pcc
          make
          
      - name: Test h5bench SYNC Read & Write (NON)
        run: |
          cd build_sync
          ./h5bench_write /home/runner/work/h5bench/h5bench/h5bench_patterns/sample_config/sample_cc1d_small.cfg file.h5
          ./h5bench_read /home/runner/work/h5bench/h5bench/h5bench_patterns/sample_config/sample_cc1d_small.cfg file.h5
