name: lint

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "Python Lint"
          path: h5bench
          config: tox.ini
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}