name: NERSC

on:
  workflow_dispatch:
  push:

jobs:
  synchronize:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Synchronize NERSC CI
        run: |
          curl --request POST --header "PRIVATE-TOKEN: ${{ secrets.NERSC_GITLAB_TOKEN }}" "${{ secrets.NERSC_GITLAB_URL }}"
